steps:
# build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA', '.']
# Push the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA']
# Deploy the container image to Cloud Run
 # Create the GKE cluster
- name: 'gcr.io/cloud-builders/gcloud'
  args:
      - container
      - clusters
      - create
      - clusterlab # Remplacez par le nom de votre cluster
      - --zone=us-central1-a # Remplacez par la zone de votre cluster (ex: us-central1-a)
      - --machine-type=e2-medium
      - --num-nodes=1
 # Deploy the application to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
      - apply
      - -f
      - GKE.yaml # Remplacez par le nom de votre fichier de déploiement Kubernetes
  env:
      - CLOUDSDK_COMPUTE_ZONE=us-central1-a # Remplacez par la zone de votre cluster
      - CLOUDSDK_CONTAINER_CLUSTER=clusterlab # Remplacez par le nom de votre cluster
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY

