steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - fetch_ci # Nom de votre fonction
  - --runtime=python312
  - --trigger-http
  - --allow-unauthenticated
  - --requirements=requirements.txt
  - --region=global # Remplacez par votre region (ex: us-central1)
